name: Prod Autobuild

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: wolf0110 
          password: ${{ secrets.DOCKERTOKEN }}
      - uses: actions/checkout@v3	
      - name: Build and Publish to Hub
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: wolf0110/se-node-red:latest
  notify-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: build
    steps:
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.MS_WEBHOOK }}
        message: "<strong>PROD</strong> SE-NodeRED Autobuild <strong style='color: green;'>SUCCSESS</strong>"
  notify-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: build
    steps:
    - name: Send a Notification
      id: notify
      uses: thechetantalwar/teams-notify@v2
      with:
        teams_webhook_url: ${{ secrets.MS_WEBHOOK }}
        message: "<strong>DEV</strong> SE-NodeRED Autobuild <strong style='color: red;'>FAILED</strong>"